# Generated by Django 4.2.10 on 2024-08-20 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_balance_updated_at_subscription_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество бонусов'),
        ),
    ]
