# Generated by Django 4.2.10 on 2024-08-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_group_students'),
        ('users', '0005_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('course', 'subscriber')},
        ),
    ]
