# Generated by Django 4.2.10 on 2024-08-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_is_access_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_access',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
    ]
